name: Auto release

on:
  push:
    branches:
      - main
    paths:
      - "OpenAPIGenerator/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner-os: ubuntu-latest
            dotnet-target: linux-x64
          - runner-os: windows-latest
            dotnet-target: win-x64
          - runner-os: macos-latest
            dotnet-target: osx-arm64
          - runner-os: macos-26-intel
            dotnet-target: osx-x64
    runs-on: ${{ matrix.runner-os }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.x

      - name: Build and publish for ${{ matrix.dotnet-target }}
        run: |
          cd OpenAPIGenerator
          dotnet restore
          dotnet build -c Release
          dotnet publish -c Release -r ${{ matrix.dotnet-target }} --self-contained true -o ./publish/${{ matrix.dotnet-target }}

      - name: Upload the OpenAPIGenerator-${{matrix.dotnet-target}} artifact
        uses: actions/upload-artifact@v7
        with:
          name: OpenAPIGenerator-${{ matrix.dotnet-target }}
          path: ./OpenAPIGenerator/publish/${{ matrix.dotnet-target }}/**

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v8
        with:
          skip-decompress: true

      - uses: softprops/action-gh-release@v3
        with:
          tag_name: nightly
          prerelease: true
          overwrite_files: true
          files: ./OpenAPIGenerator-*/OpenAPIGenerator-*.zip
